# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: anthropomorphy
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This site is the weblog of David Ham.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://anthropomorphy.org # the base hostname & protocol for your site, e.g. http://example.com

# Social
twitter_username: davidham_actual
github_username:  davidham

show_excerpts: true

pretty_url: false


# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

gitlab-letsencrypt:
  # Gitlab settings:
  gitlab_repo:           'davidham/anthropomorphy' # Namespaced repository identifier

  # Domain settings:
  email:                 'me@davidham.com'     # Let's Encrypt email address
  domain:                'anthropomorphy.org'             # Domain that the cert will be issued for

  # Jekyll settings:
  base_path:  '/'               # Where you want the file to go
  pretty_url: true              # Add a "/" on the end of the URL... set to `true` if you use permalink_style: pretty
  permalink_style: pretty

  filename:   'letsencrypt.html' # What to call the generated challenge file
  append_str: "index.html"
  # Delay settings:
  initial_delay: 120 # How long to wait for Gitlab CI to push your changes before it starts checking
  delay_time:     15 # How long to wait between each check once it starts looking for the file

  # Optional settings you probably don't need:
  # gitlab_url: 'https://someurl'  # Set if you need to use a self-hosted GitLab instance
  # endpoint:  'https://somewhere' # if you're doing the ACME thing outside of letsencrypt
  # branch:    'master'            # Defaults to master, but you can use a different branch
  # layout:    'null'              # Layout to use for challenge file - defaults to null, but you can change if needed
  # scheme:    'https'             # Scheme to use for challenge request; default http
